### ISSUE TITLE
README.md code example uses incorrect import statement?

### ISSUE THREAD

**Issue by alexjlockwood** [angular/material-prefix-updater#5] opened 2017-09-22 17:50 UTC
The `README.md` file suggests to use the following code:

```
import {MATERIAL_COMPATIBILITY_MODE} from '@angular/material';
```

However, this only works when you use `@angular/material/core`.

**Comment by jelbourn** [comment] 2017-09-22 18:36
@alexjlockwood are you use beta.11? I was able to import that symbol in the material.angular.io app.

**Comment by Splaktar** [comment] 2017-09-25 20:02
Just `@angular/material` works for me. Angular 4.4.3, AM beta.11, and TypeScript 2.3.4.

**Comment by DevVersion** [comment] 2017-10-16 15:29
I was not able to reproduce this issue either. I'll be closing this issue for now, but please drop another message if you still run into the same issue.

**Closed by DevVersion** 2017-10-16 15:29 UTC
Labels: in-progress
